x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release of Pelican.
    releaseTypes:
      - Feature
    recommended: true
  clusterConstraints:
    assistedClusterCreation:
      type: STRICT
      gke:
        nodePool:
        - numNodes: 1
          machineType: n1-standard-4
  images:
    '':
      properties:
        pelican.image.repo:
          type: REPO_WITH_REGISTRY
        pelican.image.tag:
          type: TAG
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reporting-secret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  pelican.service.loadBalancerSourceRanges:
    type: string
    title: Web UI Access Source IP Adress
    description: Comma separated source IPs/CIDRs to restrict application URL access, e.g. 114.162.90.75/32,115.132.81.56/32
    default: "0.0.0.0/0"
  pelican.persistence.storageClass:
    type: string
    title: StorageClass for Pelican Application
    description: Created StorageClass provisioner will be "pd-ssd".
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
required:
  - name
  - namespace
  - pelican.service.loadBalancerSourceRanges
