# Default values for raven application
ubb:
  image:
    repo: null
    tag: null
  port: 3456

ravendb:
  image:
    repo: null
    tag: null
  port: 5432
  replicas: 1
  persistence:
    size: 60Gi

raven:
  replicas: 1
  namespace: "default"
  image:
    repo: null
    tag: null
  service:
    type: LoadBalancer
    port: 8443
    targetPort: 8443
    loadBalancerSourceRanges:
  storage:
    bucket: raven-web-app-gke-deloyer-demo
    dir: /opt/raven/raven-data
  pvc:
    storage: 60Gi
  ssl:
    enabled: true
    tls:
      base64EncodedPrivateKey: null
      base64EncodedCertificate: null
