x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release of Pelican.
    releaseTypes:
      - Feature
    recommended: true
  images:
    '':
      properties:
        pelican.image.repo:
          type: REPO_WITH_REGISTRY
        pelican.image.tag:
          type: TAG
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  pelicandb.mysqlpassword:
    type: string
    title: Bucket name
    description: Bucket name for storage of input files and other data.
  reporting_secret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
required:
  - name
  - namespace