apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: pelican-db
spec:
  serviceName: {{ .Release.Name }}-db-service
  replicas: {{ .Values.pelicandb.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: pelican-db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pelican-db
    spec:
      containers:
      - name: pelican-db
        image: "{{ .Values.pelicandb.image.repo }}:{{ .Values.pelicandb.image.tag }}"
        imagePullPolicy: Always
        args:
          - "--ignore-db-dir=lost+found"
        env:
           - name: MARIADB_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 key: MARIADB_ROOT_PASSWD
                 name: {{ .Release.Name }}-secret
           - name: MARIADB_USER
             value: pelicanuser
           - name: MARIADB_PASSWORD
             valueFrom:
               secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MARIADB_PELICAN_PASSWD    
        ports:
        - name: mariadb
          containerPort: {{ .Values.pelicandb.port }}
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d/init-db.sql
          subPath: init-db.sql
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - 127.0.0.1
          initialDelaySeconds: {{ .Values.pelicandb.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.pelicandb.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.pelicandb.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.pelicandb.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.pelicandb.livenessProbe.failureThreshold }}
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - 127.0.0.1
          initialDelaySeconds: {{ .Values.pelicandb.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.pelicandb.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.pelicandb.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.pelicandb.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.pelicandb.readinessProbe.failureThreshold }}
      restartPolicy: Always
      volumes:
      - name: init-db
        configMap:
          name: {{ .Release.Name }}-init-db
          defaultMode: 420
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/component: pelican-db
    spec:
      resources:
        requests:
          storage: {{ .Values.pelicandb.persistence.size }}
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ .Values.pelican.persistence.storageClass }}
