apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pelicandb-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: pelicandb-secret
type: Opaque
data:
  mysqlpassword: {{ .Values.pelicandb.mysqlPassword }}
