apiVersion: v1
kind: Secret
metadata: 
    name: {{ .Release.Name }}-secret
type: Opaque
data:
   MARIADB_ROOT_PASSWD: {{ .Values.pelicandb.password.root_passwd }}
   MARIADB_PELICAN_PASSWD: {{ .Values.pelicandb.password.pelican_passwd }}
