apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ubbagent-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ubbagent
data:
  disk-only.yaml: |
    name: null
    title: null
    producer_project_id: null
    identities:
    - name: gcp
      gcp:
        encodedServiceAccountKey: $AGENT_ENCODED_KEY
    control:
      environment: null
    metrics:
    - name: null
      metric_kind: null
      value_type: null
      type: int
      unit: 1
      endpoints:
      - name: null
      - name: null
      passthrough: {}
    endpoints:
    - name: null
      disk:
        reportDir: /var/ubbagent/reports
        expireSeconds: 3600
    - name: null
      servicecontrol:
        identity: null
        serviceName: null
        consumerId: $AGENT_CONSUMER_ID
    billing:
      metrics:
      - null
      rules:
      - selector: "*"
        allowed_statuses:
        - current