apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: raven-web
spec:
  type: {{ .Values.raven.service.type }}
  # Kubernetes allows traffic from ip's defined in loadBalancerSourceRanges
  loadBalancerSourceRanges:
  {{- range $IP := (split "," .Values.raven.service.loadBalancerSourceRanges) }}
    - {{ $IP }}
  {{- end }}
  ports:
    - name: ravenui-2
      port: {{ .Values.raven.service.port }}
      protocol: TCP
      targetPort: {{ .Values.raven.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: raven-web
    app: raven-web

