apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: raven-db
spec:
  serviceName: {{ .Release.Name }}-db-service
  replicas: {{ .Values.ravendb.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: raven-db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: raven-db
    spec:
      containers:
        - name: raven-db
          image:  "{{ .Values.ravendb.image.repo }}:{{ .Values.ravendb.image.tag }}"
          ports:
            - containerPort: {{ .Values.ravendb.port }}
              name: postgredb
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumes:
      - name: {{ .Release.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
