{{- if .Values.raven.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssl-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: raven-ssl-secrets
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.raven.ssl.tls.base64EncodedPrivateKey }}
  tls.crt: {{ .Values.raven.ssl.tls.base64EncodedCertificate }}
{{ end }}
